# Generated by Django 5.2.17 on 2026-08-29 17:53

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auctions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("wallet", "المحفظة"),
                            ("insurance_free", "تأمين متاح"),
                            ("insurance_held", "تأمين محجوز لمزاد"),
                            ("insurance_locked", "تأمين مقفول لمستحقات"),
                            ("confiscated", "تأمين مصادَر"),
                            ("revenue", "إيرادات"),
                            ("suspense", "معلّق — وصلنا ولم نعرف صاحبه"),
                            ("external_cash", "خارجي — تحويل بنكي"),
                            ("external_card", "خارجي — بطاقة"),
                            ("external_refund", "خارجي — استرداد مدفوع"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=64, unique=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة"),
                            ("open", "مستحقة"),
                            ("partial", "مسدَّدة جزئياً"),
                            ("paid", "مسدَّدة"),
                            ("cancelled", "ملغاة"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("odoo_state_raw", models.CharField(blank=True, max_length=64)),
                (
                    "odoo_invoice_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("issued_at", models.DateTimeField()),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="auctions.vehicle",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("insurance_topup", "إيداع تأمين"),
                            ("insurance_hold", "حجز تأمين لمزاد"),
                            ("insurance_release", "فك حجز التأمين"),
                            ("insurance_lock", "قفل التأمين على مستحقات"),
                            ("insurance_unlock", "فك القفل بعد السداد"),
                            ("insurance_refund", "استرداد تأمين"),
                            ("insurance_confiscate", "مصادرة تأمين"),
                            ("wallet_topup", "شحن المحفظة"),
                            ("wallet_withdraw", "سحب من المحفظة"),
                            ("invoice_payment", "سداد فاتورة"),
                            ("unattributed_receipt", "مبلغ وصل بلا صاحب"),
                            ("attribution", "نسب مبلغ معلّق لصاحبه"),
                            ("correction", "تصحيح"),
                            ("reversal", "عكس قيد"),
                        ],
                        max_length=32,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=200, unique=True)),
                ("occurred_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("memo", models.CharField(blank=True, max_length=500)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The operator who caused this, when a human did.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reverses",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversed_by",
                        to="money.transaction",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Hold",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("bidding", "ضمان المزايدة"),
                            ("dues", "مقابل مستحقات غير مسدَّدة"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("active", "قائم"),
                            ("released", "مفكوك"),
                            ("consumed", "استُهلك"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("exception_note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "auction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="holds",
                        to="auctions.auction",
                    ),
                ),
                (
                    "exception_granted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="holds",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="holds",
                        to="money.invoice",
                    ),
                ),
                (
                    "created_by_transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="holds_created",
                        to="money.transaction",
                    ),
                ),
                (
                    "ended_by_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="holds_ended",
                        to="money.transaction",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="money.account",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="money.transaction",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["owner", "kind"], name="money_accou_owner_i_299d20_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="account",
            constraint=models.UniqueConstraint(
                fields=("owner", "kind"), name="one_account_per_owner_and_kind"
            ),
        ),
        migrations.AddConstraint(
            model_name="account",
            constraint=models.UniqueConstraint(
                condition=models.Q(("owner__isnull", True)),
                fields=("kind",),
                name="one_singleton_account_per_kind",
            ),
        ),
        migrations.AddConstraint(
            model_name="account",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        (
                            "kind__in",
                            (
                                "wallet",
                                "insurance_free",
                                "insurance_held",
                                "insurance_locked",
                            ),
                        ),
                        _negated=True,
                    ),
                    ("balance__gte", Decimal("0.00")),
                    _connector="OR",
                ),
                name="customer_buckets_never_go_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="account",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        (
                            "kind__in",
                            (
                                "wallet",
                                "insurance_free",
                                "insurance_held",
                                "insurance_locked",
                            ),
                        ),
                        ("owner__isnull", False),
                    ),
                    ("owner__isnull", True),
                    _connector="OR",
                ),
                name="customer_buckets_must_have_an_owner",
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["customer", "state"], name="money_invoi_custome_0622d4_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gte", Decimal("0.00"))),
                name="invoice_amount_not_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount_paid__gte", Decimal("0.00"))),
                name="invoice_paid_not_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("vehicle__isnull", False),
                    models.Q(("state", "cancelled"), _negated=True),
                ),
                fields=("vehicle",),
                name="one_live_invoice_per_vehicle",
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["kind", "-occurred_at"], name="money_trans_kind_55b5f9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["-created_at"], name="money_trans_created_1faa06_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hold",
            index=models.Index(
                fields=["owner", "state"], name="money_hold_owner_i_dcba59_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="hold",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", Decimal("0.00"))),
                name="hold_is_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="hold",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("ended_by_transaction__isnull", True), ("state", "active")
                    ),
                    models.Q(("state", "active"), _negated=True),
                    _connector="OR",
                ),
                name="active_hold_has_not_ended",
            ),
        ),
        migrations.AddConstraint(
            model_name="hold",
            constraint=models.UniqueConstraint(
                condition=models.Q(("auction__isnull", False), ("state", "active")),
                fields=("owner", "auction"),
                name="one_active_hold_per_customer_and_auction",
            ),
        ),
        migrations.AddIndex(
            model_name="entry",
            index=models.Index(
                fields=["account", "id"], name="money_entry_account_15d842_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="entry",
            index=models.Index(
                fields=["owner", "id"], name="money_entry_owner_i_4daa88_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="entry",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount", Decimal("0.00")), _negated=True),
                name="entry_is_not_zero",
            ),
        ),
    ]
