# Generated by Django 5.2.17 on 2026-09-02 10:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0001_initial"),
        ("money", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="hold",
            constraint=models.UniqueConstraint(
                condition=models.Q(("invoice__isnull", False), ("state", "active")),
                fields=("owner", "invoice"),
                name="one_active_hold_per_customer_and_invoice",
            ),
        ),
        migrations.AddConstraint(
            model_name="hold",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("auction__isnull", False),
                    ("invoice__isnull", False),
                    _connector="OR",
                ),
                name="a_hold_names_its_subject",
            ),
        ),
    ]
