# Generated by Django 5.2.17 on 2026-09-02 12:37

from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0001_initial"),
        ("money", "0001_initial"),
        ("odoo", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentIntent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference", models.CharField(max_length=64, unique=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("currency", models.CharField(default="SAR", max_length=3)),
                (
                    "purpose",
                    models.CharField(
                        choices=[("insurance_deposit", "إيداع تأمين")], max_length=32
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "بانتظار الدفع"),
                            ("succeeded", "تمت"),
                            ("failed", "فشلت"),
                            ("cancelled", "ألغاها العميل"),
                            ("expired", "انتهت مهلتها"),
                            ("disputed", "محل نزاع"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("gateway", models.CharField(default="moyasar", max_length=32)),
                (
                    "gateway_payment_id",
                    models.CharField(blank=True, db_index=True, max_length=128),
                ),
                ("gateway_status_raw", models.CharField(blank=True, max_length=64)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "auction",
                    models.ForeignKey(
                        blank=True,
                        help_text="المزاد الذي طُلب التأمين من أجله، إن وُجد",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_intents",
                        to="auctions.auction",
                    ),
                ),
                (
                    "resulting_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_intents",
                        to="money.transaction",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_intents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="money_payme_user_id_2a6f3e_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("amount__gt", Decimal("0.00"))),
                        name="payment_intent_is_positive",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("gateway_payment_id", ""), _negated=True),
                        fields=("gateway", "gateway_payment_id"),
                        name="one_intent_per_gateway_payment",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("state", "succeeded"), _negated=True),
                            ("resulting_transaction__isnull", False),
                            _connector="OR",
                        ),
                        name="a_succeeded_intent_names_its_transaction",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RefundRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("reference", models.CharField(max_length=64, unique=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("requested", "مُقدَّم"),
                            ("sent", "أُرسل للمحاسبة"),
                            ("confirmed", "نُفِّذ"),
                            ("rejected", "مرفوض"),
                            ("cancelled", "ألغاه العميل"),
                        ],
                        default="requested",
                        max_length=16,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "outbox_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refund_requests",
                        to="odoo.outboxmessage",
                    ),
                ),
                (
                    "resulting_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refund_requests",
                        to="money.transaction",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refund_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="money_refun_user_id_25570f_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("amount__gt", Decimal("0.00"))),
                        name="refund_request_is_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("state", "confirmed"), _negated=True),
                            ("resulting_transaction__isnull", False),
                            _connector="OR",
                        ),
                        name="a_confirmed_refund_names_its_transaction",
                    ),
                ],
            },
        ),
    ]
