# Generated by Django 5.2.17 on 2026-09-02 15:18

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("money", "0003_merge_wallet_and_hold_constraints"),
        ("odoo", "0003_alter_inboundmessage_payload_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="account",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("kind", "suspense"), _negated=True),
                    ("balance__gte", Decimal("0.00")),
                    _connector="OR",
                ),
                name="suspense_never_goes_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="refundrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("state__in", ("requested", "sent"))),
                fields=("user",),
                name="one_open_refund_request_per_customer",
            ),
        ),
    ]
