# Generated by Django 5.2.17 on 2026-09-02 15:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_vehicle_condition_vehicle_fuel_type_and_more"),
        ("money", "0004_account_suspense_never_goes_negative_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount_paid__lte", models.F("amount"))),
                name="invoice_paid_not_above_amount",
            ),
        ),
    ]
