# Generated by Django 5.2.17 on 2026-09-07 04:04

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0006_invoice_names_its_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digest', models.CharField(max_length=64, unique=True)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('rows_read', models.PositiveIntegerField(default=0)),
                ('rows_posted', models.PositiveIntegerField(default=0)),
                ('rows_skipped', models.PositiveIntegerField(default=0)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_sheets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'دفعة مرفوعة',
                'verbose_name_plural': 'الدفعات المرفوعة',
                'ordering': ['-uploaded_at', '-id'],
            },
        ),
    ]
