# Generated by Django 5.2.17 on 2026-09-08 22:04

import apps.core.uploads
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("money", "0007_paymentsheet"),
        ("odoo", "0005_refund_shortfall_queue"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BankTopupRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("reference", models.CharField(max_length=64, unique=True)),
                (
                    "receipt",
                    models.FileField(upload_to=apps.core.uploads.bank_receipt_path),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("submitted", "قيد المراجعة"),
                            ("posted", "اعتُمد وأُضيف للرصيد"),
                            ("rejected", "مرفوض"),
                            ("cancelled", "ألغاه العميل"),
                        ],
                        default="submitted",
                        max_length=16,
                    ),
                ),
                ("admin_note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "outbox_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bank_topups",
                        to="odoo.outboxmessage",
                    ),
                ),
                (
                    "resulting_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bank_topups",
                        to="money.transaction",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bank_topups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="money_bankt_user_id_143045_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("amount__gt", Decimal("0.00"))),
                        name="bank_topup_is_positive",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("state", "submitted")),
                        fields=("user",),
                        name="one_open_bank_topup_per_customer",
                    ),
                ],
            },
        ),
    ]
