# Generated by Django 5.2.17 on 2026-09-09 17:15

import django.db.models.expressions
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0011_vehicle_is_hidden"),
        ("money", "0008_banktopuprequest"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="admin_fee",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=14
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="net_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=14
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="tax_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=14
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("admin_fee", Decimal("0.00")),
                        ("net_amount", Decimal("0.00")),
                        ("tax_amount", Decimal("0.00")),
                    ),
                    (
                        "amount",
                        django.db.models.expressions.CombinedExpression(
                            django.db.models.expressions.CombinedExpression(
                                models.F("net_amount"), "+", models.F("admin_fee")
                            ),
                            "+",
                            models.F("tax_amount"),
                        ),
                    ),
                    _connector="OR",
                ),
                name="invoice_parts_add_up_to_its_total",
            ),
        ),
    ]
