# Generated by Django 5.2.17 on 2026-09-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("money", "0009_invoice_admin_fee_invoice_net_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentintent",
            name="expires_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="paymentintent",
            name="gateway_checkout_id",
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AddField(
            model_name="paymentintent",
            name="gateway_checkout_url",
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
