# Generated by Django 5.2.17 on 2026-09-14 15:00

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("money", "0010_payment_intent_checkout_and_expiry"),
        ("odoo", "0005_refund_shortfall_queue"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # عنوانُ الحالة وحده — لا شيء في القاعدة يتغيّر به (`choices` وصفٌ في
        # بايثون). وهو هنا لا في هجرةٍ ثانية لأن التغييرَين واحد: صار الموظّف
        # يعتمد ما وصل، فلم تعد «أُضيف للرصيد» صادقةً في كلّ اعتماد.
        migrations.AlterField(
            model_name="banktopuprequest",
            name="state",
            field=models.CharField(
                choices=[
                    ("submitted", "قيد المراجعة"),
                    ("posted", "اعتُمد وقُيِّد"),
                    ("rejected", "مرفوض"),
                    ("cancelled", "ألغاه العميل"),
                ],
                default="submitted",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="banktopuprequest",
            name="amount_approved",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="banktopuprequest",
            name="bank_iban",
            field=models.CharField(blank=True, max_length=34),
        ),
        migrations.AddField(
            model_name="banktopuprequest",
            name="bank_sender_name",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="banktopuprequest",
            name="bank_transfer_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="banktopuprequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("amount_approved__isnull", True),
                    ("amount_approved__gt", Decimal("0.00")),
                    _connector="OR",
                ),
                name="an_approved_bank_topup_amount_is_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="banktopuprequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("state", "posted"), _negated=True),
                    ("amount_approved__isnull", False),
                    _connector="OR",
                ),
                name="a_posted_bank_topup_names_its_approved_amount",
            ),
        ),
    ]
