# Generated by Django 5.2.17 on 2026-09-18 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("money", "0011_bank_topup_matching_fields"),
        ("odoo", "0005_refund_shortfall_queue"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="refundrequest",
            name="decided_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="refundrequest",
            name="decided_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="refundrequest",
            name="decision_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddConstraint(
            model_name="refundrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("state", "rejected"), _negated=True),
                    models.Q(
                        models.Q(("decision_note", ""), _negated=True),
                        ("decided_by__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="a_refused_refund_names_its_decision",
            ),
        ),
    ]
