# Generated by Django 5.2.17 on 2026-09-18 11:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("money", "0012_refundrequest_decided_at_refundrequest_decided_by_and_more"),
        ("odoo", "0005_refund_shortfall_queue"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="refundrequest",
            name="a_refused_refund_names_its_decision",
        ),
        migrations.AlterField(
            model_name="refundrequest",
            name="state",
            field=models.CharField(
                choices=[
                    ("requested", "مُقدَّم"),
                    ("sent", "أُرسل للمحاسبة"),
                    ("confirmed", "نُفِّذ"),
                    ("rejected", "مرفوض"),
                    ("cancelled", "ألغاه العميل"),
                    ("v1_paid", "صُرف في v1"),
                ],
                default="requested",
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="refundrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("state", "rejected"), _negated=True),
                    models.Q(("decision_note", ""), _negated=True),
                    _connector="OR",
                ),
                name="a_refused_refund_names_its_decision",
            ),
        ),
    ]
