# Generated by Django 5.2.17 on 2026-09-21 23:28

import apps.core.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0013_remove_refundrequest_a_refused_refund_names_its_decision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsheet',
            name='receipt',
            field=models.FileField(blank=True, max_length=255, upload_to=apps.core.uploads.bank_receipt_path),
        ),
    ]
