# Generated by Django 5.2.17 on 2026-09-29 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0014_payment_sheet_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='refundrequest',
            name='iban',
            field=models.CharField(blank=True, max_length=34, verbose_name='الآيبان'),
        ),
    ]
