# Generated by Django 5.2.17 on 2026-10-07 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0015_refund_request_iban'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton', models.BooleanField(default=True, editable=False, unique=True)),
                ('beneficiary', models.CharField(blank=True, max_length=200, verbose_name='المستفيد')),
                ('bank', models.CharField(blank=True, max_length=120, verbose_name='البنك')),
                ('iban', models.CharField(max_length=34, verbose_name='الآيبان')),
                ('account', models.CharField(blank=True, max_length=40, verbose_name='رقم الحساب')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('iban__regex', '^SA[0-9]{22}$')), name='company_bank_iban_is_saudi')],
            },
        ),
    ]
