# Generated by Django 5.2.17 on 2026-08-29 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("money", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BalanceCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ours", models.DecimalField(decimal_places=2, max_digits=14)),
                ("theirs", models.DecimalField(decimal_places=2, max_digits=14)),
                ("difference", models.DecimalField(decimal_places=2, max_digits=14)),
                ("method", models.CharField(max_length=64)),
                ("detail", models.JSONField(blank=True, default=dict)),
                ("checked_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="balance_checks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-checked_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-checked_at"],
                        name="odoo_balanc_user_id_76b4fe_idx",
                    ),
                    models.Index(
                        fields=["-checked_at"], name="odoo_balanc_checked_857a51_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CustomerLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("odoo_customer_id", models.CharField(db_index=True, max_length=64)),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="الحساب الذي تُنسب إليه الحركات الجديدة",
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("linked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "linked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="odoo_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "odoo_customer_id"), name="one_link_per_pair"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_primary", True)),
                        fields=("odoo_customer_id",),
                        name="one_primary_account_per_odoo_customer",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="InboundMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        help_text="odoo | moyasar | manual", max_length=32
                    ),
                ),
                ("event", models.CharField(blank=True, max_length=64)),
                ("delivery_id", models.CharField(blank=True, max_length=128)),
                (
                    "subject_ref",
                    models.CharField(blank=True, db_index=True, max_length=128),
                ),
                ("payload", models.JSONField()),
                ("headers", models.JSONField(blank=True, default=dict)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("received", "مستلَمة"),
                            ("processed", "معالَجة"),
                            ("ignored", "متجاهَلة عمداً"),
                            ("failed", "فشلت — قابلة لإعادة التشغيل"),
                        ],
                        default="received",
                        max_length=16,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "resulting_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="from_messages",
                        to="money.transaction",
                    ),
                ),
            ],
            options={
                "ordering": ["-received_at"],
                "indexes": [
                    models.Index(
                        fields=["state", "received_at"],
                        name="odoo_inboun_state_d63286_idx",
                    ),
                    models.Index(
                        fields=["source", "event", "-received_at"],
                        name="odoo_inboun_source_51611f_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("delivery_id", ""), _negated=True),
                        fields=("source", "delivery_id"),
                        name="one_row_per_delivery",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="OutboxMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("endpoint", models.CharField(max_length=120)),
                ("payload", models.JSONField()),
                ("reference", models.CharField(max_length=128, unique=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "بالانتظار"),
                            ("sent", "أُرسلت"),
                            ("confirmed", "مؤكَّدة من أودو"),
                            ("failed", "فشلت"),
                            ("abandoned", "متروكة بقرار"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("last_error", models.TextField(blank=True)),
                ("response", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "source_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outbox_messages",
                        to="money.transaction",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["state", "created_at"],
                        name="odoo_outbox_state_93ab64_idx",
                    )
                ],
            },
        ),
    ]
