# Generated by Django 5.2.17 on 2026-09-02 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("odoo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inboundmessage",
            name="odoo_database",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name="inboundmessage",
            name="raw_body",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="inboundmessage",
            name="state",
            field=models.CharField(
                choices=[
                    ("received", "مستلَمة"),
                    ("processed", "معالَجة"),
                    ("ignored", "متجاهَلة عمداً"),
                    ("failed", "فشلت — قابلة لإعادة التشغيل"),
                    ("rejected_signature", "توقيع مرفوض"),
                ],
                default="received",
                max_length=24,
            ),
        ),
    ]
