# Generated by Django 5.2.17 on 2026-09-02 15:18

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("odoo", "0002_inboundmessage_odoo_database_inboundmessage_raw_body_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inboundmessage",
            name="payload",
            field=models.JSONField(
                encoder=django.core.serializers.json.DjangoJSONEncoder
            ),
        ),
        migrations.AlterField(
            model_name="outboxmessage",
            name="payload",
            field=models.JSONField(
                encoder=django.core.serializers.json.DjangoJSONEncoder
            ),
        ),
        migrations.AlterField(
            model_name="outboxmessage",
            name="response",
            field=models.JSONField(
                blank=True,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                null=True,
            ),
        ),
    ]
