# Generated by Django 5.2.17 on 2026-09-05 15:02

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odoo', '0004_unverified_messages_own_no_delivery_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundShortfall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_ref', models.CharField(db_index=True, max_length=128)),
                ('requested', models.DecimalField(decimal_places=2, max_digits=14)),
                ('free', models.DecimalField(decimal_places=2, max_digits=14)),
                ('held', models.DecimalField(decimal_places=2, max_digits=14)),
                ('locked', models.DecimalField(decimal_places=2, max_digits=14)),
                ('shortfall', models.DecimalField(decimal_places=2, max_digits=14)),
                ('note', models.TextField(blank=True)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution', models.TextField(blank=True)),
                ('message', models.ForeignKey(help_text='الرسالة الواردة التي طلبت السحب', on_delete=django.db.models.deletion.PROTECT, related_name='refund_shortfalls', to='odoo.inboundmessage')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refund_shortfalls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'عجز استرداد',
                'verbose_name_plural': 'طابور عجز الاسترداد',
                'indexes': [models.Index(fields=['resolved_at', 'opened_at'], name='odoo_refund_resolve_a411bb_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('shortfall__gt', Decimal('0.00'))), name='a_shortfall_is_a_shortfall'), models.UniqueConstraint(fields=('refund_ref',), name='one_shortfall_per_refund_request'), models.CheckConstraint(condition=models.Q(('resolved_at__isnull', True), models.Q(models.Q(('resolution', ''), _negated=True), ('resolved_by__isnull', False)), _connector='OR'), name='a_closed_shortfall_names_its_decision')],
            },
        ),
    ]
