"""أين يُرسَل العميل ليدفع — وهو سؤالٌ للخادم لا للعميل.

The contract had a hole and both channels fell into it: `start_topup` writes a
:class:`~apps.money.models.PaymentIntent` and returns it, but nothing in that
row said **where the customer goes to pay**. The web could create an intent and
not send anybody anywhere; phase 008's card top-up would have hit the same wall.

The shape this fills it with is deliberately not "a gateway url in the response"
-------------------------------------------------------------------------------
The obvious fix is to put the gateway's own address in the serialized intent.
It is the wrong one, for a reason that outlives whichever gateway is chosen:

* every gateway wants something different — a redirect for one, a form `POST`
  with signed fields for the next, a session token for a third. A field holding
  "the gateway url" is a field whose meaning changes when the gateway does, and
  **both clients would have to change with it**;
* and the shape would leak into two codebases that have no business knowing it.
  The web and the app would each grow a branch for "how do we hand off to
  Moyasar", which is a rule living in three places (Article 4-5).

So the intent carries a url on **our own** server, always the same shape, and
that endpoint is where the handoff is decided. Switching gateway is then a
change here and nowhere else — neither client is rebuilt, neither is redeployed,
and neither ever learns what a Moyasar is.

Off by default, like every other integration
--------------------------------------------
With no `PAYMENT_CHECKOUT_TEMPLATE` configured this module produces nothing and
the endpoint refuses in Arabic. That is the same stance the Odoo client and the
payment callback take: an integration that is not configured must refuse rather
than guess, because the guess is a customer sent to a broken page with money in
their hand.
"""

from __future__ import annotations

from urllib.parse import quote

from django.conf import settings

from .models import PaymentIntent, PaymentIntentState

__all__ = ["CheckoutUnavailable", "checkout_target", "is_payable"]


class CheckoutUnavailable(Exception):
    """No gateway is configured, or this intent can no longer be paid.

    One exception for both, with the Arabic sentence chosen by the raiser: to a
    customer they are the same situation — this button will not take them
    anywhere — and to an operator the two are told apart by which sentence
    appears in the log.
    """

    def __init__(self, user_message: str):
        super().__init__(user_message)
        self.user_message = user_message


def is_payable(intent: PaymentIntent) -> bool:
    """Whether sending this customer to a gateway could still do anything.

    Only a `pending` intent. A succeeded one would take a second payment for a
    deposit already made; a failed or cancelled one is a row somebody would be
    paying against after the platform stopped expecting it. Both are cases where
    the *absence* of a button is the correct interface.
    """
    return intent.state == PaymentIntentState.PENDING


def checkout_target(intent: PaymentIntent) -> str:
    """Where to send this customer, right now, to pay this intent.

    Built from a configured template rather than assembled in code, so the
    gateway is an environment decision and not a deployment. The template names
    what it needs:

        PAYMENT_CHECKOUT_TEMPLATE="https://pay.example.com/{reference}?amount={amount}"

    ``reference`` is the only identifier that crosses. It is ours, it is opaque,
    and it is what a returning payment is attributed by — the gateway never
    learns a user id, which is the whole reason `PaymentIntent` exists as a row
    written before the customer leaves (v1 tried to recover the customer from
    the return url and lost payments that way).

    ``amount`` is included because most gateways want it echoed, and it is the
    server's figure from `deposit_amount_for` — never a number a client named.
    It is substituted as the decimal *string* the ledger stores, so nothing on
    this path turns an amount into a float (Article 3-2).
    """
    if not is_payable(intent):
        raise CheckoutUnavailable("هذه العملية لم تعد قابلة للدفع.")

    template = getattr(settings, "PAYMENT_CHECKOUT_TEMPLATE", "")
    if not template:
        raise CheckoutUnavailable("الدفع بالبطاقة غير مفعّل في هذه البيئة.")

    # `quote` on every substituted value: a reference is generated by us and is
    # url-safe today, and a template that only works because of that is a
    # template that breaks the day a gateway wants a different reference format.
    return template.format(
        reference=quote(intent.reference, safe=""),
        amount=quote(str(intent.amount), safe=""),
        currency=quote(intent.currency, safe=""),
    )
