[project]
name = "haraj-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "argon2-cffi>=25.1.0",
    "celery[redis]>=5.6.3",
    "django>=5.2,<6",
    "django-environ>=0.14.0",
    "django-filter>=26.1",
    "djangorestframework>=3.18.0",
    "drf-spectacular>=0.30.0",
    "pillow>=12.3.0",
    "psycopg[binary]>=3.3.4",
    "redis>=6.4.0",
]

[dependency-groups]
dev = [
    "django-stubs>=6.1.0",
    "factory-boy>=3.3.3",
    "mypy>=2.3.1",
    "pytest>=9.1.1",
    "pytest-django>=4.14.0",
    "ruff>=0.16.5",
]

[tool.ruff]
line-length = 90
target-version = "py313"

[tool.ruff.lint]
select = ["E", "F", "I", "UP", "B", "DJ"]
