# Generated by Django 5.2.17 on 2026-09-14 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_device"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Broadcast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("sms", "رسالة نصية"),
                            ("push", "إشعار"),
                            ("in_app", "داخل التطبيق"),
                        ],
                        max_length=16,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=120)),
                ("body", models.TextField()),
                ("audience", models.JSONField(blank=True, default=dict)),
                ("audience_label", models.CharField(blank=True, max_length=300)),
                ("recipient_count", models.PositiveIntegerField(default=0)),
                (
                    "unit_cost",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=8, null=True
                    ),
                ),
                (
                    "estimated_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=120, unique=True)),
                ("reason", models.TextField(blank=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "في الطابور"),
                            ("running", "قيد الإدراج"),
                            ("done", "أُدرج"),
                            ("failed", "فشل"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("queued_count", models.PositiveIntegerField(default=0)),
                ("failed_count", models.PositiveIntegerField(default=0)),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="broadcasts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["-created_at"], name="broadcast_recent"),
                    models.Index(
                        fields=["state", "created_at"], name="broadcast_state"
                    ),
                ],
            },
        ),
    ]
