# Generated by Django 5.2.17 on 2026-09-14 15:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NewsTickerMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text_ar",
                    models.CharField(max_length=255, verbose_name="النص (عربي)"),
                ),
                (
                    "text_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="النص (إنجليزي)"
                    ),
                ),
                (
                    "starts_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="يبدأ العرض"
                    ),
                ),
                (
                    "ends_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="ينتهي العرض"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="مفعّلة")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "رسالة شريط أخبار",
                "verbose_name_plural": "رسائل شريط الأخبار",
                "ordering": ("-created_at", "-id"),
                "indexes": [
                    models.Index(
                        fields=["is_active", "starts_at", "ends_at"],
                        name="news_ticker_active_time",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("starts_at__isnull", True),
                            ("ends_at__isnull", True),
                            ("ends_at__gte", models.F("starts_at")),
                            _connector="OR",
                        ),
                        name="news_window_ends_after_it_starts",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("text_ar", ""), _negated=True),
                        name="news_text_ar_not_blank",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="اسم الباقة")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="مبلغ التأمين"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                (
                    "period",
                    models.CharField(
                        choices=[("1", "شهر واحد"), ("2", "٣ أشهر"), ("3", "٦ أشهر")],
                        default="1",
                        max_length=1,
                        verbose_name="المدّة",
                    ),
                ),
                (
                    "auction_quota",
                    models.PositiveIntegerField(
                        default=0, verbose_name="حصّة المزادات"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="مفعّلة")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "باقة",
                "verbose_name_plural": "الباقات",
                "ordering": ("price", "-id"),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("price__gte", Decimal("0"))),
                        name="package_price_not_negative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("name", ""), _negated=True),
                        name="package_name_not_blank",
                    ),
                ],
            },
        ),
    ]
