# Generated by Django 5.2.17 on 2026-08-29 17:53

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Auction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveIntegerField(
                        help_text="رقم المزاد المعروض", unique=True
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة"),
                            ("scheduled", "مجدول"),
                            ("live", "جارٍ"),
                            ("ended", "منتهٍ"),
                            ("settled", "مُسوّى"),
                            ("cancelled", "ملغى"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                (
                    "deposit_required",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("10000.00"), max_digits=14
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-starts_at"],
                "indexes": [
                    models.Index(
                        fields=["state", "starts_at"],
                        name="auctions_au_state_4ddee1_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("ends_at__gt", models.F("starts_at"))),
                        name="auction_ends_after_it_starts",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lot_number",
                    models.PositiveIntegerField(help_text="رقم اللوت داخل المزاد"),
                ),
                ("make", models.CharField(max_length=80)),
                ("model", models.CharField(max_length=120)),
                ("year", models.PositiveSmallIntegerField()),
                ("vin", models.CharField(blank=True, db_index=True, max_length=32)),
                ("plate_number", models.CharField(blank=True, max_length=16)),
                ("plate_type", models.CharField(blank=True, max_length=32)),
                ("odometer_km", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "reserve_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة"),
                            ("listed", "معروضة"),
                            ("bidding", "تحت المزايدة"),
                            ("awaiting_decision", "بانتظار قرار المالك"),
                            ("awarded", "مرسّاة"),
                            ("rejected", "مرفوضة"),
                            ("invoiced", "مفوترة"),
                            ("paid", "مسدَّدة"),
                            ("released", "خرجت"),
                            ("withdrawn", "مسحوبة"),
                            ("relisted", "معادة للعرض"),
                        ],
                        default="draft",
                        max_length=24,
                    ),
                ),
                (
                    "awarded_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("awarded_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "auction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vehicles",
                        to="auctions.auction",
                    ),
                ),
                (
                    "awarded_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="won_vehicles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner_company",
                    models.ForeignKey(
                        blank=True,
                        help_text="الشريك المالك للمركبة، إن وُجد",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vehicles",
                        to="accounts.company",
                    ),
                ),
            ],
            options={
                "ordering": ["auction", "lot_number"],
            },
        ),
        migrations.CreateModel(
            name="VehicleImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="vehicles/%Y/%m/")),
                ("position", models.PositiveSmallIntegerField(default=0)),
                ("is_cover", models.BooleanField(default=False)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="auctions.vehicle",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="vehicle",
            index=models.Index(
                fields=["auction", "state"], name="auctions_ve_auction_755cc1_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="vehicle",
            constraint=models.UniqueConstraint(
                fields=("auction", "lot_number"), name="one_lot_number_per_auction"
            ),
        ),
        migrations.AddConstraint(
            model_name="vehicle",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("awarded_to__isnull", False), ("state", "awarded")),
                    models.Q(("state", "awarded"), _negated=True),
                    _connector="OR",
                ),
                name="an_awarded_vehicle_names_its_winner",
            ),
        ),
        migrations.AddConstraint(
            model_name="vehicleimage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_cover", True)),
                fields=("vehicle",),
                name="one_cover_image_per_vehicle",
            ),
        ),
    ]
