# Generated by Django 5.2.17 on 2026-09-02 12:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("auctions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="condition",
            field=models.CharField(
                choices=[
                    ("running", "تسير"),
                    ("not_running", "لا تسير"),
                    ("damaged", "متضررة"),
                    ("salvage", "تشليح"),
                    ("unknown", "غير محدد"),
                ],
                default="unknown",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="fuel_type",
            field=models.CharField(
                choices=[
                    ("petrol", "بنزين"),
                    ("diesel", "ديزل"),
                    ("hybrid", "هجين"),
                    ("electric", "كهرباء"),
                    ("unknown", "غير محدد"),
                ],
                default="unknown",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="transmission",
            field=models.CharField(
                choices=[
                    ("automatic", "أوتوماتيك"),
                    ("manual", "عادي"),
                    ("cvt", "CVT"),
                    ("unknown", "غير محدد"),
                ],
                default="unknown",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="vehicleimage",
            name="thumbnail",
            field=models.ImageField(blank=True, upload_to="vehicles/%Y/%m/thumbs/"),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="plate_type",
            field=models.CharField(
                choices=[
                    ("private", "خصوصي"),
                    ("public_transport", "نقل عام"),
                    ("taxi", "أجرة"),
                    ("heavy", "نقل ثقيل"),
                    ("export", "تصدير"),
                    ("none", "بدون لوحة"),
                ],
                default="private",
                max_length=32,
            ),
        ),
        migrations.AddIndex(
            model_name="vehicle",
            index=models.Index(
                fields=["owner_company", "state"], name="auctions_ve_owner_c_dc9e01_idx"
            ),
        ),
    ]
