# Generated by Django 5.2.17 on 2026-09-05 14:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_user_console_role_staffgrant"),
        ("auctions", "0004_upload_paths_are_generated"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="vehicle",
            constraint=models.UniqueConstraint(
                condition=models.Q(("vin", ""), _negated=True),
                fields=("auction", "vin"),
                name="one_vin_per_auction",
            ),
        ),
    ]
