# Generated by Django 5.2.17 on 2026-09-05 18:43

import apps.core.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0005_a_vin_enters_an_auction_once"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicleimage",
            name="preview",
            field=models.ImageField(
                blank=True, upload_to=apps.core.uploads.vehicle_preview_path
            ),
        ),
    ]
