# Generated by Django 5.2.17 on 2026-09-06 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0006_a_photograph_has_a_preview_tier"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="location",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="colour",
            field=models.CharField(
                choices=[
                    ("white", "أبيض"),
                    ("black", "أسود"),
                    ("silver", "فضي"),
                    ("grey", "رمادي"),
                    ("blue", "أزرق"),
                    ("dark_blue", "أزرق غامق"),
                    ("red", "أحمر"),
                    ("green", "أخضر"),
                    ("gold", "ذهبي"),
                    ("beige", "بيج"),
                    ("brown", "بني"),
                    ("yellow", "أصفر"),
                    ("other", "لون آخر"),
                    ("unknown", "غير محدد"),
                ],
                default="unknown",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="condition",
            field=models.CharField(
                choices=[
                    ("running", "تسير"),
                    ("not_running", "لا تسير"),
                    ("accident", "حادث"),
                    ("fire", "حريق"),
                    ("flood", "غرق"),
                    ("damaged", "متضررة"),
                    ("salvage", "تشليح"),
                    ("unknown", "غير محدد"),
                ],
                default="unknown",
                max_length=16,
            ),
        ),
    ]
