# Generated by Django 5.2.17 on 2026-09-06 22:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0007_a_card_shows_what_v1_shows"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="admin_fee",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("800.00"), max_digits=14
            ),
        ),
    ]
