# Generated by Django 5.2.17 on 2026-09-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0008_a_bidding_screen_shows_the_admin_fee"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="showcase",
            field=models.CharField(
                choices=[
                    ("later", "لاحقاً — مخفيّ عن العملاء"),
                    ("upcoming", "قادم — معلَن بلا عدّاد"),
                    ("soon", "قريباً — معلَن بعدّاد"),
                ],
                default="upcoming",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="auction",
            name="sms_reminder_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
