# Generated by Django 5.2.17 on 2026-09-07 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0009_a_pre_start_auction_has_a_showcase"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="claim_number",
            field=models.CharField(blank=True, db_index=True, max_length=60),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="insurance_company",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="is_marketing",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="key_status",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="runs_status",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
