# Generated by Django 5.2.17 on 2026-09-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_five_fields_from_the_v1_vehicles_screen'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
