# Generated by Django 5.2.17 on 2026-09-09 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0011_vehicle_is_hidden"),
        ("bidding", "0003_alter_bidrefusal_reason"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="partner_decided_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="partner_decided_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="partner_rulings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="partner_decision",
            field=models.CharField(
                blank=True,
                choices=[
                    ("accepted", "قبل الشريك العرض"),
                    ("rejected", "رفض الشريك العروض"),
                ],
                default="",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="partner_decision_bid",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="partner_rulings",
                to="bidding.bid",
            ),
        ),
    ]
