# Generated by Django 5.2.17 on 2026-09-09 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0012_vehicle_partner_decided_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="reminder_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
