# Generated by Django 5.2.17 on 2026-09-10 02:50

import apps.auctions.exits
import apps.core.uploads
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auction_reminder_sent_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleExit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('created', 'تم إنشاء الخروج'), ('under_transfer', 'قيد متابعة النقل'), ('archived', 'منقولة (أرشيف)')], default='created', max_length=20)),
                ('barcode', models.CharField(default=apps.auctions.exits._new_barcode, max_length=24, unique=True)),
                ('exit_reason', models.CharField(blank=True, max_length=200)),
                ('recipient_name', models.CharField(blank=True, max_length=200)),
                ('recipient_id', models.CharField(blank=True, max_length=40)),
                ('recipient_phone', models.CharField(blank=True, max_length=20)),
                ('declaration_file', models.FileField(blank=True, upload_to=apps.core.uploads.exit_declaration_path)),
                ('transfer_proof_file', models.FileField(blank=True, upload_to=apps.core.uploads.exit_proof_path)),
                ('warehouse_exit_at', models.DateTimeField(blank=True, null=True)),
                ('transfer_at', models.DateTimeField(blank=True, null=True)),
                ('ban_lifted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='exit_order', to='auctions.vehicle')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['stage'], name='auctions_ve_stage_0c17da_idx')],
            },
        ),
    ]
