# Generated by Django 5.2.17 on 2026-09-10 03:07

import apps.core.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_vehicleexit'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleexit',
            name='recipient_id_image',
            field=models.FileField(blank=True, upload_to=apps.core.uploads.exit_declaration_path),
        ),
    ]
