# Generated by Django 5.2.17 on 2026-09-10 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_vehicleexit_recipient_id_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleexit',
            name='declaration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
