# Generated by Django 5.2.17 on 2026-09-14 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_vehicleexit_declaration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleexit',
            name='exit_type',
            field=models.CharField(blank=True, choices=[('after_transfer', 'خروج بعد النقل (تمّ نقل الملكية)'), ('without_transfer', 'خروج بدون نقل (بانتظار النقل)'), ('repair_inspection', 'خروج للإصلاح والفحص')], db_index=True, max_length=24),
        ),
        migrations.AlterField(
            model_name='vehicleexit',
            name='exit_reason',
            field=models.CharField(blank=True, choices=[('no_problem', 'خروج بدون مشكلة'), ('no_plates_no_inspection', 'بدون لوحات / لا يوجد فحص'), ('no_plates_ban', 'بدون لوحات / حظر')], max_length=200),
        ),
        migrations.AlterField(
            model_name='vehicleexit',
            name='stage',
            field=models.CharField(choices=[('created', 'تم إنشاء الخروج'), ('sent_to_gate', 'بانتظار البوابة'), ('under_transfer', 'قيد متابعة النقل'), ('archived', 'منقولة (أرشيف)')], default='created', max_length=20),
        ),
    ]
