# Generated by Django 5.2.17 on 2026-09-22 00:29

import apps.core.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_exit_type_and_gate_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='payment_receipt',
            field=models.FileField(blank=True, max_length=255, upload_to=apps.core.uploads.bank_receipt_path),
        ),
    ]
