# Generated by Django 5.2.17 on 2026-09-02 12:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=64)),
                ("entity_type", models.CharField(max_length=64)),
                ("entity_id", models.CharField(max_length=64)),
                ("before", models.JSONField(blank=True, default=None, null=True)),
                ("after", models.JSONField(blank=True, default=None, null=True)),
                ("at", models.DateTimeField(default=django.utils.timezone.now)),
                ("note", models.TextField(blank=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["entity_type", "entity_id", "-at"],
                        name="core_auditl_entity__33a993_idx",
                    ),
                    models.Index(
                        fields=["actor", "-at"], name="core_auditl_actor_i_b5d7d1_idx"
                    ),
                    models.Index(
                        fields=["action", "-at"], name="core_auditl_action_f262f3_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("action", ""), _negated=True),
                        name="audit_action_is_named",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("entity_type", ""), _negated=True),
                            models.Q(("entity_id", ""), _negated=True),
                        ),
                        name="audit_entity_is_named",
                    ),
                ],
            },
        ),
    ]
