/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auctions/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * قائمة المزادات
         * @description `GET /api/v1/auctions/` — the auctions a caller may see, newest first.
         */
        get: operations["auctions_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auctions/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * تفاصيل المزاد
         * @description `GET /api/v1/auctions/{id}/` — one auction, in the list's own shape.
         *
         *     Built by `cards.auction_card` with the same annotations the list uses, so
         *     the detail page and the row a customer tapped cannot disagree about how many
         *     cars an auction holds. An auction the caller may not see is a 404: a 403
         *     would confirm it exists, which is enough to enumerate auctions before they
         *     open.
         */
        get: operations["auctions_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auctions/{id}/vehicles/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * مركبات المزاد
         * @description `GET /api/v1/auctions/{id}/vehicles/` — one auction's cars.
         */
        get: operations["auctions_vehicles_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/code/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * إرسال رمز تحقق
         * @description `POST /api/v1/auth/code/` — send a one-time code to a mobile number.
         */
        post: operations["v1_auth_code_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/phone/change/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * بدء تغيير رقم الجوال
         * @description `POST /api/v1/auth/phone/change/` — send a code to both numbers.
         *
         *     The only path in this file that requires a signed-in caller, and the number
         *     being left is read **off the token**, never off the request body. Letting the
         *     body name the current number would make this endpoint a way to move somebody
         *     else's account, which is the shape of the takeover it exists to close.
         */
        post: operations["v1_auth_phone_change_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/phone/change/confirm/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * تأكيد تغيير الجوال بالرمزين
         * @description `POST /api/v1/auth/phone/change/confirm/` — both codes, or nothing.
         *
         *     Answers 200 with the caller's own account, whose `phone` is the new number.
         *     Every session — this one included — is revoked by the service, so the client
         *     signs in again on the new number; that is deliberate, and
         *     `services.confirm_phone_change` says why.
         */
        post: operations["v1_auth_phone_change_confirm_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * تجديد رمز الوصول
         * @description `POST /api/v1/auth/refresh/` — spend a refresh token for a fresh pair.
         */
        post: operations["v1_auth_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/verify/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * التحقق من الرمز وإصدار الرموز
         * @description `POST /api/v1/auth/verify/` — exchange a correct code for a token pair.
         */
        post: operations["v1_auth_verify_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bids/{id}/withdraw/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * سحب مزايدة
         * @description `POST /api/v1/bids/{id}/withdraw/` — pull a bid back.
         *
         *     The bid is fetched **filtered by the caller** rather than fetched and then
         *     checked, so somebody else's bid id is a 404 and not a 403. The service
         *     refuses it a second time anyway (`NotYourBid`) — the two guards are not
         *     redundant: this one decides what a stranger learns, that one is the rule.
         */
        post: operations["bids_withdraw"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bids/mine/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * مزايداتي
         * @description `GET /api/v1/bids/mine/` — the caller's own bids, and only those.
         */
        get: operations["bids_mine"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * أجهزتي
         * @description `POST`/`GET /api/v1/devices/` — register this handset, or list mine.
         */
        get: operations["devices_list"];
        put?: never;
        /**
         * تسجيل جهاز للإشعارات
         * @description `POST`/`GET /api/v1/devices/` — register this handset, or list mine.
         */
        post: operations["devices_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invoices/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_invoices_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invoices/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_invoices_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invoices/{id}/pay/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Settle one invoice from the balance the customer already has with us.
         *
         *     There is no card branch here and no card purpose to reach for: a purchase is
         *     paid from deposited money or by a bank transfer the bank confirms. */
        post: operations["v1_invoices_pay_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payments/callback/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description The gateway telling us what happened. The only path that credits a card.
         *
         *     Stored raw and acknowledged before anything interprets it (Article 2-1), and
         *     never dropped: a message we cannot use is kept with the reason written on it
         *     (Article 2-2). */
        post: operations["v1_payments_callback_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profile/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * ملفي الشخصي
         * @description `GET`/`PATCH /api/v1/profile/` — the caller's own account.
         */
        get: operations["profile_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * تعديل الملف الشخصي
         * @description `GET`/`PATCH /api/v1/profile/` — the caller's own account.
         */
        patch: operations["profile_update"];
        trace?: never;
    };
    "/api/v1/profile/company/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * ملف الشركة
         * @description `GET`/`PUT /api/v1/profile/company/` — the company and its ZATCA address.
         */
        get: operations["profile_company_retrieve"];
        /**
         * حفظ ملف الشركة
         * @description `GET`/`PUT /api/v1/profile/company/` — the company and its ZATCA address.
         */
        put: operations["profile_company_save"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profile/national-id/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * تثبيت رقم الهوية
         * @description `PUT /api/v1/profile/national-id/` — set it once it is right.
         *
         *     A valid id already on the account is refused (`national_id_already_verified`);
         *     an invalid one may be replaced. `services.set_national_id` says why at
         *     length — the short version is that a customer who mistyped a digit must be
         *     able to fix themselves, and a correct id must not be swappable for
         *     somebody else's.
         */
        put: operations["profile_set_national_id"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/purchases/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Vehicles awarded to the caller, each with its live invoice. */
        get: operations["v1_purchases_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vehicles/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * قائمة المركبات
         * @description `GET /api/v1/vehicles/` — cars across auctions, searched and filtered.
         */
        get: operations["vehicles_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vehicles/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * تفاصيل المركبة
         * @description `GET /api/v1/vehicles/{id}/` — one car, through the one card builder.
         *
         *     T609's whole requirement is that this returns the *same* fields as the list.
         *     It does so by construction rather than by discipline: both call
         *     `cards.vehicle_card`, and there is no second assembly of a vehicle anywhere
         *     (`ops/checks/one_vehicle_card.py` fails the build if one appears).
         *
         *     A car the caller may not see is a 404, not a 403. A 403 confirms the row
         *     exists, which is enough to enumerate an auction before it opens.
         */
        get: operations["vehicles_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vehicles/{id}/bids/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * وضع مزايدة
         * @description `POST /api/v1/vehicles/{id}/bids/` — bid, or be told exactly why not.
         *
         *     Lowering a standing bid is refused the first time with
         *     `lower_needs_confirm` and accepted when the caller comes back with
         *     ``confirm_lower``. That two-step is T506: lowering is a real feature of a
         *     sealed auction and also exactly what a fat finger does, so it costs one
         *     deliberate extra round trip.
         *
         *     The car is resolved through `visible_vehicles`, so bidding on something the
         *     caller cannot see is a 404 — the same answer as a car that does not exist,
         *     which is what stops the endpoint being used to probe an unopened auction.
         */
        post: operations["bids_place"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wallet/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The customer's money, split by the pot it is actually sitting in. */
        get: operations["v1_wallet_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wallet/refund-requests/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_wallet_refund_requests_list"];
        put?: never;
        post: operations["v1_wallet_refund_requests_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wallet/topups/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Start a card top-up, or list the ones this customer started. */
        get: operations["v1_wallet_topups_list"];
        put?: never;
        /** @description Start a card top-up, or list the ones this customer started. */
        post: operations["v1_wallet_topups_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wallet/topups/{reference}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Where the customer lands on return from the gateway.
         *
         *     It reads one stored row and answers with it. Not a single query parameter is
         *     consulted — a return URL is under the payer's thumb, and in v1 that was
         *     enough to make the app believe a payment had succeeded. Money moves in
         *     :class:`PaymentCallbackView` and nowhere else. */
        get: operations["v1_wallet_topups_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wallet/transactions/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Every ledger line belonging to the caller, newest first, paginated. */
        get: operations["v1_wallet_transactions_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description The auction row, as `cards.auction_card` builds it. */
        AuctionCard: {
            id: number;
            number: number;
            title: string;
            state: string;
            state_label: string;
            /** Format: date-time */
            starts_at: string;
            /** Format: date-time */
            ends_at: string;
            vehicle_count: number | null;
            open_vehicle_count: number | null;
        };
        AuctionPage: {
            total: number;
            results: components["schemas"]["AuctionCard"][];
        };
        /** @description The caller's own account. Never anybody else's — the view reads it off
         *     the token, never off a request field. */
        AuthenticatedUser: {
            id: number;
            phone: string;
            display_name: string;
            account_type: string;
            is_new: boolean;
        };
        /** @description A bid as the owner of it sees it.
         *
         *     Never anybody else's: a sealed auction's whole property is that bidders
         *     cannot see each other's numbers, so there is no endpoint here that lists the
         *     bids *on* a car — only the bids *by* the caller. */
        Bid: {
            id: number;
            vehicle_id: number;
            auction_id: number;
            lot_number: number;
            vehicle_title: string;
            amount: string;
            /** Format: date-time */
            placed_at: string;
            is_withdrawn: boolean;
            is_superseded: boolean;
        };
        BidPage: {
            total: number;
            results: components["schemas"]["Bid"][];
        };
        /** @description One named pot, with the count of entries that add up to it. */
        Bucket: {
            kind: string;
            label: string;
            /** Format: decimal */
            amount: string;
            entry_count: number;
            /** @description Where to read the exact entries behind this number (Article 1-6). */
            readonly statement: string;
        };
        /** @description The company and its ZATCA national address.
         *
         *     Nothing is `required` at this layer even though most of it is required for a
         *     *new* company: the exemption for companies that predate ZATCA's national
         *     address is a business rule with a date attached, and business rules live in
         *     the service layer. A serializer that hard-coded `required=True` would refuse
         *     an existing company its own edit form. */
        CompanyProfile: {
            name?: string;
            representative_name?: string;
            commercial_register?: string;
            vat_number?: string;
            building_number?: string;
            street?: string;
            district?: string;
            city?: string;
            postal_code?: string;
        };
        /** @description The same fields plus whether they add up to something invoiceable. */
        CompanyProfileRead: {
            name?: string;
            representative_name?: string;
            commercial_register?: string;
            vat_number?: string;
            building_number?: string;
            street?: string;
            district?: string;
            city?: string;
            postal_code?: string;
            readonly is_complete: boolean;
        };
        /** @description Both codes, in one request.
         *
         *     One request, not two, and that is the rule rather than a convenience: two
         *     requests would mean a server-side half-finished state in which one number is
         *     proven and the other is not — which is exactly the single-proof change that
         *     T604 exists to make impossible. */
        ConfirmPhoneChange: {
            new_phone: string;
            /** @description الرمز المُرسَل إلى الرقم الحالي */
            current_code: string;
            /** @description الرمز المُرسَل إلى الرقم الجديد */
            new_code: string;
        };
        /** @description A registered handset, as its owner sees it. */
        Device: {
            id: number;
            platform: string;
            /** Format: date-time */
            created_at: string;
            /** @description آخر ستة أحرف، للتمييز فقط */
            token_tail: string;
        };
        /** @description One handset, identified by the token its push provider issued. */
        DeviceRegistration: {
            token: string;
            platform: components["schemas"]["PlatformEnum"];
        };
        /** @description A claim on part of the customer's insurance, and what it is claimed for. */
        Hold: {
            readonly id: number;
            /** Format: decimal */
            amount: string;
            reason: components["schemas"]["ReasonEnum"];
            readonly reason_label: string;
            readonly auction: {
                [key: string]: unknown;
            } | null;
            readonly invoice: {
                [key: string]: unknown;
            } | null;
            /** Format: date-time */
            readonly created_at: string;
        };
        Invoice: {
            readonly id: number;
            number: string;
            /** Format: decimal */
            readonly amount: string;
            /** Format: decimal */
            readonly amount_paid: string;
            /** Format: decimal */
            readonly outstanding: string;
            state?: components["schemas"]["InvoiceStateEnum"];
            readonly state_label: string;
            /** Format: date-time */
            issued_at: string;
            /** Format: date-time */
            due_at?: string | null;
            /** @description The only two ways a purchase is ever paid for. Card is not one. */
            readonly payment_methods: {
                [key: string]: unknown;
            }[];
        };
        /** @description ``method`` accepts only what :class:`PaymentMethod` declares.
         *
         *     ``card`` is not a member, so the schema itself rejects it and there is no
         *     branch anywhere that could accidentally grow one. */
        InvoicePay: {
            /** @default balance */
            method: components["schemas"]["MethodEnum"];
        };
        /**
         * @description * `draft` - مسودة
         *     * `open` - مستحقة
         *     * `partial` - مسدَّدة جزئياً
         *     * `paid` - مسدَّدة
         *     * `cancelled` - ملغاة
         * @enum {string}
         */
        InvoiceStateEnum: "draft" | "open" | "partial" | "paid" | "cancelled";
        /** @description One line of the statement, read straight off an ``Entry`` row. */
        LedgerEntry: {
            id: number;
            /** Format: uuid */
            transaction: string;
            kind: string;
            readonly description: string;
            bucket: string;
            readonly bucket_label: string;
            /** Format: decimal */
            amount: string;
            readonly direction: string;
            /** Format: date-time */
            occurred_at: string;
            memo: string;
        };
        /**
         * @description * `balance` - من الرصيد
         *     * `bank_transfer` - تحويل بنكي
         * @enum {string}
         */
        MethodEnum: "balance" | "bank_transfer";
        /** @description Ten digits. Whether they are a *valid* identity is the service's call.
         *
         *     The length check is here because it is a property of the field; the checksum
         *     is not, because T606's rule — a correct id is pinned, a wrong one may be
         *     corrected — needs one definition of "correct" and it lives in
         *     `apps.accounts.identity`. */
        NationalId: {
            national_id: string;
        };
        PaginatedInvoiceList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?offset=400&limit=100
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?offset=200&limit=100
             */
            previous?: string | null;
            results: components["schemas"]["Invoice"][];
        };
        PaginatedLedgerEntryList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?offset=400&limit=100
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?offset=200&limit=100
             */
            previous?: string | null;
            results: components["schemas"]["LedgerEntry"][];
        };
        PaginatedPurchaseList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?offset=400&limit=100
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?offset=200&limit=100
             */
            previous?: string | null;
            results: components["schemas"]["Purchase"][];
        };
        /** @description What a customer may change about themselves, and nothing else.
         *
         *     Every field here is optional, and `validate` refuses an empty body: a PATCH
         *     that changes nothing is almost always a client bug, and answering 200 to it
         *     hides the bug behind a success.
         *
         *     Unknown keys are refused rather than dropped (T605). DRF's default is to
         *     ignore them, which turns a client's typo into a silent no-op — the customer
         *     presses save, sees no error, and the value never changes. */
        PatchedProfileUpdate: {
            full_name?: string;
            email?: string;
        };
        PaymentIntent: {
            reference: string;
            /** Format: decimal */
            readonly amount: string;
            currency?: string;
            purpose: components["schemas"]["PaymentIntentPurposeEnum"];
            readonly purpose_label: string;
            state?: components["schemas"]["PaymentIntentStateEnum"];
            readonly state_label: string;
            gateway?: string;
            gateway_status_raw?: string;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /**
         * @description * `insurance_deposit` - إيداع تأمين
         * @enum {string}
         */
        PaymentIntentPurposeEnum: "insurance_deposit";
        /**
         * @description * `pending` - بانتظار الدفع
         *     * `succeeded` - تمت
         *     * `failed` - فشلت
         *     * `cancelled` - ألغاها العميل
         *     * `expired` - انتهت مهلتها
         *     * `disputed` - محل نزاع
         * @enum {string}
         */
        PaymentIntentStateEnum: "pending" | "succeeded" | "failed" | "cancelled" | "expired" | "disputed";
        /** @description One bid on one car. */
        PlaceBid: {
            amount: string;
            /** @default false */
            confirm_lower: boolean;
        };
        /**
         * @description * `android` - android
         *     * `ios` - ios
         *     * `web` - web
         * @enum {string}
         */
        PlatformEnum: "android" | "ios" | "web";
        /** @description The caller's own account, as a screen shows it.
         *
         *     Read-only fields are marked as such rather than merely ignored on write:
         *     a client generated from this schema then cannot offer a form field that
         *     silently does nothing, which is how v1's "edit profile" screen let people
         *     type a new phone number into a box that never saved it. */
        Profile: {
            readonly id: number;
            /** @description يتغيّر عبر مسار خاص */
            readonly phone: string;
            readonly display_name: string;
            full_name: string;
            email?: string;
            readonly account_type: string;
            readonly national_id: string;
            readonly national_id_verified: boolean;
            /** Format: date-time */
            readonly phone_verified_at: string | null;
            readonly has_company_profile: boolean;
            readonly company_profile_complete: boolean;
        };
        /** @description A vehicle this customer won, with the invoice that followed it. */
        Purchase: {
            id: number;
            lot_number: number;
            make: string;
            model: string;
            year: number;
            state: string;
            /** Format: decimal */
            awarded_price: string;
            /** Format: date-time */
            awarded_at: string;
            readonly auction: {
                [key: string]: unknown;
            };
            readonly invoice: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * @description * `bidding` - ضمان المزايدة
         *     * `dues` - مقابل مستحقات غير مسدَّدة
         * @enum {string}
         */
        ReasonEnum: "bidding" | "dues";
        Refresh: {
            refresh: string;
        };
        RefundRequest: {
            readonly id: number;
            reference: string;
            /** Format: decimal */
            readonly amount: string;
            state?: components["schemas"]["RefundRequestStateEnum"];
            readonly state_label: string;
            /** Format: date-time */
            readonly created_at: string;
        };
        RefundRequestCreate: {
            /** Format: decimal */
            amount: string;
        };
        /**
         * @description * `requested` - مُقدَّم
         *     * `sent` - أُرسل للمحاسبة
         *     * `confirmed` - نُفِّذ
         *     * `rejected` - مرفوض
         *     * `cancelled` - ألغاه العميل
         * @enum {string}
         */
        RefundRequestStateEnum: "requested" | "sent" | "confirmed" | "rejected" | "cancelled";
        /** @description Ask for a code. */
        SendCode: {
            phone: string;
            /** @default login */
            purpose: components["schemas"]["SendCodePurposeEnum"];
        };
        /**
         * @description * `login` - دخول أو تسجيل
         *     * `change_phone` - تغيير رقم الجوال
         *     * `recover` - استعادة الحساب
         * @enum {string}
         */
        SendCodePurposeEnum: "login" | "change_phone" | "recover";
        /** @description What the caller learns: that it went, and when it stops working. */
        SendCodeResponse: {
            sent: boolean;
            /** Format: date-time */
            expires_at: string;
            /** @description ثوانٍ حتى يُسمح بطلب رمز جديد */
            resend_after: number;
        };
        /** @description Ask for the pair of codes that a phone change needs. */
        StartPhoneChange: {
            new_phone: string;
        };
        /** @description That both messages went, and when they stop working.
         *
         *     Two booleans rather than one, because the screen has to tell the customer to
         *     go and look at two phones — one of which may be in a drawer. */
        StartPhoneChangeResponse: {
            sent_to_current: boolean;
            sent_to_new: boolean;
            /** Format: date-time */
            expires_at: string;
            /** @description ثوانٍ حتى يُسمح بطلب رمز جديد */
            resend_after: number;
        };
        TokenPair: {
            access: string;
            refresh: string;
            /** @description عمر رمز الوصول بالثواني */
            expires_in: number;
            /** Format: date-time */
            expires_at: string;
            user?: components["schemas"]["AuthenticatedUser"];
        };
        /** @description A request to start a card top-up. It carries no amount, by design. */
        TopupCreate: {
            auction?: number | null;
        };
        /** @description The vehicle card — the same fields in the list and on the detail page.
         *
         *     T609's acceptance criterion is that those two are identical, and
         *     `test_vehicle_api.py` asserts it by comparing the key sets rather than by
         *     reading this class, so the guarantee does not depend on this file being
         *     kept honest by hand. */
        VehicleCard: {
            id: number;
            auction_number: number;
            auction_state: string;
            lot_number: number;
            title: string;
            make: string;
            model: string;
            year: number;
            odometer_km: number | null;
            transmission: string;
            transmission_label: string;
            fuel_type: string;
            fuel_type_label: string;
            condition: string;
            condition_label: string;
            plate_type: string;
            plate_type_label: string;
            reserve_price: string | null;
            state: string;
            state_label: string;
            listing_state: string;
            owner_company_name: string | null;
            thumbnail_url: string | null;
        };
        VehiclePage: {
            total: number;
            results: components["schemas"]["VehicleCard"][];
        };
        /** @description Prove the number. */
        VerifyCode: {
            phone: string;
            code: string;
            /** @description يُستعمل عند إنشاء الحساب لأول مرة فقط */
            full_name?: string;
        };
        Wallet: {
            currency: string;
            /** Format: decimal */
            total: string;
            /** Format: decimal */
            available: string;
            /** Format: decimal */
            held_for_auctions: string;
            /** Format: decimal */
            locked_for_dues: string;
            buckets: components["schemas"]["Bucket"][];
            holds: components["schemas"]["Hold"][];
            /** Format: date-time */
            as_of: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auctions_list: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                /** @description * `draft` - مسودة
                 *     * `scheduled` - مجدول
                 *     * `live` - جارٍ
                 *     * `ended` - منتهٍ
                 *     * `settled` - مُسوّى
                 *     * `cancelled` - ملغى */
                state?: "draft" | "scheduled" | "live" | "ended" | "settled" | "cancelled" | "";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuctionPage"];
                };
            };
        };
    };
    auctions_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuctionCard"];
                };
            };
        };
    };
    auctions_vehicles_list: {
        parameters: {
            query?: {
                auction?: number;
                limit?: number;
                make?: string;
                offset?: number;
                search?: string;
                /** @description * `draft` - مسودة
                 *     * `listed` - معروضة
                 *     * `bidding` - تحت المزايدة
                 *     * `awaiting_decision` - بانتظار قرار المالك
                 *     * `awarded` - مرسّاة
                 *     * `rejected` - مرفوضة
                 *     * `invoiced` - مفوترة
                 *     * `paid` - مسدَّدة
                 *     * `released` - خرجت
                 *     * `withdrawn` - مسحوبة
                 *     * `relisted` - معادة للعرض */
                state?: "draft" | "listed" | "bidding" | "awaiting_decision" | "awarded" | "rejected" | "invoiced" | "paid" | "released" | "withdrawn" | "relisted" | "";
                year_from?: number;
                year_to?: number;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VehiclePage"];
                };
            };
        };
    };
    v1_auth_code_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendCode"];
                "application/x-www-form-urlencoded": components["schemas"]["SendCode"];
                "multipart/form-data": components["schemas"]["SendCode"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SendCodeResponse"];
                };
            };
        };
    };
    v1_auth_phone_change_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartPhoneChange"];
                "application/x-www-form-urlencoded": components["schemas"]["StartPhoneChange"];
                "multipart/form-data": components["schemas"]["StartPhoneChange"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartPhoneChangeResponse"];
                };
            };
        };
    };
    v1_auth_phone_change_confirm_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmPhoneChange"];
                "application/x-www-form-urlencoded": components["schemas"]["ConfirmPhoneChange"];
                "multipart/form-data": components["schemas"]["ConfirmPhoneChange"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticatedUser"];
                };
            };
        };
    };
    v1_auth_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Refresh"];
                "application/x-www-form-urlencoded": components["schemas"]["Refresh"];
                "multipart/form-data": components["schemas"]["Refresh"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
        };
    };
    v1_auth_verify_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyCode"];
                "application/x-www-form-urlencoded": components["schemas"]["VerifyCode"];
                "multipart/form-data": components["schemas"]["VerifyCode"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
        };
    };
    bids_withdraw: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Bid"];
                };
            };
        };
    };
    bids_mine: {
        parameters: {
            query?: {
                include_history?: boolean;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BidPage"];
                };
            };
        };
    };
    devices_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Device"][];
                };
            };
        };
    };
    devices_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceRegistration"];
                "application/x-www-form-urlencoded": components["schemas"]["DeviceRegistration"];
                "multipart/form-data": components["schemas"]["DeviceRegistration"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Device"];
                };
            };
        };
    };
    v1_invoices_list: {
        parameters: {
            query?: {
                /** @description عدد النتائج التي يجب إرجاعها في كل صفحة. */
                limit?: number;
                /** @description الفهرس الأولي الذي يجب البدء منه لإرجاع النتائج. */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedInvoiceList"];
                };
            };
        };
    };
    v1_invoices_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Invoice"];
                };
            };
        };
    };
    v1_invoices_pay_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["InvoicePay"];
                "application/x-www-form-urlencoded": components["schemas"]["InvoicePay"];
                "multipart/form-data": components["schemas"]["InvoicePay"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Invoice"];
                };
            };
        };
    };
    v1_payments_callback_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    profile_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
        };
    };
    profile_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedProfileUpdate"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedProfileUpdate"];
                "multipart/form-data": components["schemas"]["PatchedProfileUpdate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
        };
    };
    profile_company_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyProfileRead"];
                };
            };
        };
    };
    profile_company_save: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CompanyProfile"];
                "application/x-www-form-urlencoded": components["schemas"]["CompanyProfile"];
                "multipart/form-data": components["schemas"]["CompanyProfile"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyProfileRead"];
                };
            };
        };
    };
    profile_set_national_id: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NationalId"];
                "application/x-www-form-urlencoded": components["schemas"]["NationalId"];
                "multipart/form-data": components["schemas"]["NationalId"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
        };
    };
    v1_purchases_list: {
        parameters: {
            query?: {
                /** @description عدد النتائج التي يجب إرجاعها في كل صفحة. */
                limit?: number;
                /** @description الفهرس الأولي الذي يجب البدء منه لإرجاع النتائج. */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedPurchaseList"];
                };
            };
        };
    };
    vehicles_list: {
        parameters: {
            query?: {
                auction?: number;
                limit?: number;
                make?: string;
                offset?: number;
                search?: string;
                /** @description * `draft` - مسودة
                 *     * `listed` - معروضة
                 *     * `bidding` - تحت المزايدة
                 *     * `awaiting_decision` - بانتظار قرار المالك
                 *     * `awarded` - مرسّاة
                 *     * `rejected` - مرفوضة
                 *     * `invoiced` - مفوترة
                 *     * `paid` - مسدَّدة
                 *     * `released` - خرجت
                 *     * `withdrawn` - مسحوبة
                 *     * `relisted` - معادة للعرض */
                state?: "draft" | "listed" | "bidding" | "awaiting_decision" | "awarded" | "rejected" | "invoiced" | "paid" | "released" | "withdrawn" | "relisted" | "";
                year_from?: number;
                year_to?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VehiclePage"];
                };
            };
        };
    };
    vehicles_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VehicleCard"];
                };
            };
        };
    };
    bids_place: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlaceBid"];
                "application/x-www-form-urlencoded": components["schemas"]["PlaceBid"];
                "multipart/form-data": components["schemas"]["PlaceBid"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Bid"];
                };
            };
        };
    };
    v1_wallet_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Wallet"];
                };
            };
        };
    };
    v1_wallet_refund_requests_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefundRequest"][];
                };
            };
        };
    };
    v1_wallet_refund_requests_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefundRequestCreate"];
                "application/x-www-form-urlencoded": components["schemas"]["RefundRequestCreate"];
                "multipart/form-data": components["schemas"]["RefundRequestCreate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefundRequest"];
                };
            };
        };
    };
    v1_wallet_topups_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentIntent"][];
                };
            };
        };
    };
    v1_wallet_topups_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["TopupCreate"];
                "application/x-www-form-urlencoded": components["schemas"]["TopupCreate"];
                "multipart/form-data": components["schemas"]["TopupCreate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentIntent"];
                };
            };
        };
    };
    v1_wallet_topups_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reference: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentIntent"];
                };
            };
        };
    };
    v1_wallet_transactions_list: {
        parameters: {
            query?: {
                /** @description عدد النتائج التي يجب إرجاعها في كل صفحة. */
                limit?: number;
                /** @description الفهرس الأولي الذي يجب البدء منه لإرجاع النتائج. */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedLedgerEntryList"];
                };
            };
        };
    };
}
