"""Refuse any use of binary floating point on a money path.

Article 3-2 of the constitution: currency is ``Decimal(14, 2)``, and ``float``
is forbidden anywhere that touches money — *including in a report*. The reason
is not theoretical. ``0.1 + 0.2 != 0.3`` in binary floating point, so a ledger
that ever rounds a riyal through a float stops summing to zero, and a ledger
that does not sum to zero cannot answer "where did this number come from".

This runs as its own CI step rather than as a lint rule because it is a
constitutional check, not a style preference: a reviewer reading a failure here
should be pointed at the article, not at a rule code.

What it looks at
----------------
``backend/apps/money``, ``backend/apps/odoo`` and ``backend/apps/auctions``:
the ledger, the boundary where somebody else's JSON becomes our numbers, and
the third tree that holds money columns. ``json.loads`` turns ``10000.50`` into
a float without being asked, so the boundary matters as much as the core.

``apps/auctions`` was outside the scope until a review pointed out what lives
in it: ``Auction.deposit_required`` — which decides how much of a bidder's
insurance is actually held — plus ``Vehicle.reserve_price`` and
``Vehicle.awarded_price``, all three formatted for the API by ``cards.py`` and
``listing.py``. ``float(vehicle.reserve_price)`` there was a money path by any
reading of Article 3-2 and passed CI unchallenged.

The scope is those three trees and not all of ``backend/`` on purpose. A page
budget of ``0.3`` seconds and an ``isinstance(value, float)`` that *refuses* a
spreadsheet cell are both floats that never touch a riyal; flagging them would
only teach people to write ``# noqa`` next to the guard, and a guard people
route around watches nothing.

The AST blind spot
------------------
An AST walk sees the floats somebody *wrote*. It cannot see the ones a library
makes at run time, and the worst offender is the one this module's own scope
note names: ``json.loads`` without ``parse_float=Decimal`` produces a float from
a perfectly innocent-looking line. So there is a second, textual rule below —
inside these trees, JSON that may carry money is decoded through
``apps.core.jsonio`` and nowhere else.

Generated migrations are skipped — they are produced by ``makemigrations``
from the models, so a float in a migration means a float in a model, and the
model is where the failure should be reported.

Usage (both work; CI uses the first)::

    python ops/checks/no_float_in_money.py
    cd backend && uv run python ../ops/checks/no_float_in_money.py

Exit code 0 means clean, 1 means at least one finding. Nothing is printed on
success beyond a single confirmation line, so a green CI log stays readable.
"""

from __future__ import annotations

import ast
import sys
from collections.abc import Iterator
from dataclasses import dataclass
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
SEARCH_ROOTS = (
    REPO_ROOT / "backend" / "apps" / "money",
    REPO_ROOT / "backend" / "apps" / "odoo",
    REPO_ROOT / "backend" / "apps" / "auctions",
)

#: Generated by Django, never edited by hand. A float here is a symptom whose
#: cause lives in a model file, which this check also reads.
SKIP_DIR_NAMES = frozenset({"migrations", ".venv", "__pycache__", "node_modules"})

#: Django field classes that store binary floating point. ``FloatField`` is the
#: obvious one; ``DurationField`` and friends are safe and deliberately absent.
FORBIDDEN_FIELDS = frozenset({"FloatField"})

#: Builtins that produce a float. ``round`` is deliberately absent: it is the
#: identity on a Decimal, and rounding money is what ``Decimal.quantize`` is
#: for, so flagging it would only teach people to write ``# noqa``.
FORBIDDEN_CALLS = frozenset({"float"})


@dataclass(frozen=True)
class Finding:
    path: Path
    line: int
    what: str

    def __str__(self) -> str:
        where = self.path.relative_to(REPO_ROOT).as_posix()
        return f"{where}:{self.line}: {self.what}"


def python_files(root: Path) -> Iterator[Path]:
    for path in sorted(root.rglob("*.py")):
        if SKIP_DIR_NAMES.isdisjoint(part for part in path.parts):
            yield path


def _annotation_names(node: ast.expr | None) -> Iterator[str]:
    """Every bare name mentioned in an annotation, however nested.

    ``dict[str, float]`` and ``float | None`` both have to be caught, so the
    annotation is walked rather than matched.
    """
    if node is None:
        return
    for sub in ast.walk(node):
        if isinstance(sub, ast.Name):
            yield sub.id


def _json_decoders(tree: ast.AST) -> Iterator[tuple[int, str]]:
    """Every ``json.loads``/``json.load`` that does not ask for Decimal.

    Textual because it has to be: the float this produces exists only at run
    time, so no amount of AST walking over *our* expressions would find it.

    Any explicit ``parse_float=`` is accepted, not only ``=Decimal``. The rule
    is "say what a fractional number becomes", and the strictest answer in this
    tree is not Decimal at all — ``parsed_without_floats`` passes a function
    that *refuses* one outright, which is more than this check asks for.
    """
    for node in ast.walk(tree):
        if not isinstance(node, ast.Call):
            continue
        func = node.func
        if not (
            isinstance(func, ast.Attribute)
            and func.attr in {"loads", "load"}
            and isinstance(func.value, ast.Name)
            and func.value.id == "json"
        ):
            continue
        if not any(keyword.arg == "parse_float" for keyword in node.keywords):
            yield (
                node.lineno,
                f"json.{func.attr}(…) بلا parse_float=Decimal — "
                "استعمل apps.core.jsonio.loads",
            )


def inspect(path: Path) -> Iterator[Finding]:
    source = path.read_text(encoding="utf-8")
    try:
        tree = ast.parse(source, filename=str(path))
    except SyntaxError as exc:  # a file that will not parse is its own failure
        yield Finding(path, exc.lineno or 0, f"cannot parse: {exc.msg}")
        return

    for line, what in _json_decoders(tree):
        yield Finding(path, line, what)

    for node in ast.walk(tree):
        # float(...) and models.FloatField(...)
        if isinstance(node, ast.Call):
            func = node.func
            name = (
                func.id
                if isinstance(func, ast.Name)
                else func.attr
                if isinstance(func, ast.Attribute)
                else ""
            )
            if name in FORBIDDEN_CALLS:
                yield Finding(path, node.lineno, f"calls {name}() — use Decimal")
            elif name in FORBIDDEN_FIELDS:
                yield Finding(
                    path,
                    node.lineno,
                    f"declares {name} — money is DecimalField(max_digits=14, "
                    "decimal_places=2)",
                )

        # def f(x: float) -> float, and x: float = ...
        elif isinstance(node, ast.FunctionDef | ast.AsyncFunctionDef):
            annotations = [a.annotation for a in node.args.args]
            annotations += [a.annotation for a in node.args.kwonlyargs]
            annotations += [a.annotation for a in node.args.posonlyargs]
            annotations.append(node.returns)
            if any("float" in _annotation_names(a) for a in annotations):
                yield Finding(path, node.lineno, f"{node.name}() is annotated float")

        elif isinstance(node, ast.AnnAssign):
            if "float" in set(_annotation_names(node.annotation)):
                yield Finding(path, node.lineno, "annotated float")

        # A literal like 10.5 is a float the moment it is written.
        elif isinstance(node, ast.Constant) and isinstance(node.value, float):
            yield Finding(
                path,
                node.lineno,
                f'float literal {node.value!r} — quote it: Decimal("…")',
            )


def main() -> int:
    missing = [root for root in SEARCH_ROOTS if not root.is_dir()]
    if missing:
        for root in missing:
            print(f"no_float_in_money: {root} does not exist", file=sys.stderr)
        return 1

    findings = [
        f for root in SEARCH_ROOTS for path in python_files(root) for f in inspect(path)
    ]
    if not findings:
        print("no_float_in_money: clean — no floating point on any money path")
        return 0

    print("no_float_in_money: Article 3-2 — currency is Decimal(14,2), never float\n")
    for finding in findings:
        print(f"  {finding}")
    print(f"\n{len(findings)} finding(s).")
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
