# Generated by Django 5.2.17 on 2026-09-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LegacyRef",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_label", models.CharField(db_index=True, max_length=64)),
                ("legacy_id", models.CharField(max_length=64)),
                ("object_id", models.BigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "مفتاح مصدر",
                "verbose_name_plural": "مفاتيح المصدر",
                "indexes": [
                    models.Index(
                        fields=["model_label", "object_id"],
                        name="migration_l_model_l_2c343b_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("model_label", "legacy_id"),
                        name="one_row_per_legacy_key",
                    )
                ],
            },
        ),
    ]
