# Generated by Django 5.2.17 on 2026-09-02 12:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={"verbose_name": "شركة", "verbose_name_plural": "الشركات"},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "مستخدم", "verbose_name_plural": "المستخدمون"},
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="accounts_us_account_28efcc_idx",
        ),
        migrations.AlterField(
            model_name="user",
            name="national_id",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                max_length=12,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^9665\\d{8}$", "الرقم لازم يكون بصيغة 9665XXXXXXXX"
                    )
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="company",
            constraint=models.CheckConstraint(
                condition=models.Q(("name", ""), _negated=True),
                name="company_name_not_blank",
                violation_error_message="اسم الشركة مطلوب",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(("phone__regex", "^9665\\d{8}$")),
                name="user_phone_is_saudi_mobile",
                violation_error_message="الرقم لازم يكون بصيغة 9665XXXXXXXX",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                condition=models.Q(("national_id", ""), _negated=True),
                fields=("national_id",),
                name="user_national_id_unique_when_set",
                violation_error_message="رقم الهوية مسجَّل على حساب آخر",
            ),
        ),
    ]
