# Generated by Django 5.2.17 on 2026-09-02 19:49

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_phoneverification_authtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsFailure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('^9665\\d{8}$', 'الرقم لازم يكون بصيغة 9665XXXXXXXX')])),
                ('purpose', models.CharField(choices=[('login', 'دخول أو تسجيل'), ('change_phone', 'تغيير رقم الجوال'), ('recover', 'استعادة الحساب')], default='login', max_length=16)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'indexes': [models.Index(fields=['-created_at'], name='sms_failure_recent')],
            },
        ),
    ]
