# Generated by Django 5.2.17 on 2026-09-02 22:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_smsfailure'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='console_role',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.CreateModel(
            name='StaffGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capability', models.CharField(max_length=64)),
                ('granted', models.BooleanField(default=True)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grants_given', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'منح صلاحية',
                'verbose_name_plural': 'منح الصلاحيات',
                'constraints': [models.UniqueConstraint(fields=('user', 'capability'), name='one_grant_per_user_capability'), models.CheckConstraint(condition=models.Q(('reason', ''), _negated=True), name='grant_reason_not_blank', violation_error_message='سبب المنح أو السحب مطلوب')],
            },
        ),
    ]
