# Generated by Django 5.2.17 on 2026-09-07 14:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_console_role_staffgrant'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsoleRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=32, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('capabilities', models.JSONField(blank=True, default=list)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='roles_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'دور لوحة',
                'verbose_name_plural': 'أدوار اللوحة',
                'ordering': ('label',),
                'constraints': [models.CheckConstraint(condition=models.Q(('reason', ''), _negated=True), name='console_role_reason_not_blank', violation_error_message='سبب إنشاء الدور مطلوب')],
            },
        ),
    ]
