# Generated by Django 5.2.17 on 2026-09-07 16:31

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_a_password_written_by_another_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('individual', 'فرد'), ('company', 'شركة')], default='individual', max_length=16, verbose_name='نوع الحساب'),
        ),
        migrations.AlterField(
            model_name='user',
            name='console_role',
            field=models.CharField(blank=True, max_length=16, verbose_name='دور اللوحة'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ التسجيل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='البريد'),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='الاسم الكامل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='الحساب مفعّل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='موظّف'),
        ),
        migrations.AlterField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, verbose_name='يغيّر كلمة المرور عند أوّل دخول'),
        ),
        migrations.AlterField(
            model_name='user',
            name='national_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='رقم الهوية'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator('^9665\\d{8}$', 'الرقم لازم يكون بصيغة 9665XXXXXXXX')], verbose_name='الجوال'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت توثيق الجوال'),
        ),
    ]
