# Generated by Django 5.2.17 on 2026-09-07 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_field_labels_are_arabic_like_the_screens'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='banned_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='محظور حتى'),
        ),
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'ذكر'), ('female', 'أنثى')], max_length=8, verbose_name='الجنس'),
        ),
        migrations.AddField(
            model_name='user',
            name='iban',
            field=models.CharField(blank=True, max_length=50, verbose_name='الآيبان'),
        ),
        migrations.AddField(
            model_name='user',
            name='id_kind',
            field=models.CharField(blank=True, choices=[('national_id', 'هوية وطنية'), ('iqama', 'إقامة'), ('passport', 'جواز سفر')], max_length=16, verbose_name='نوع الهوية'),
        ),
        migrations.AddField(
            model_name='user',
            name='name_ar',
            field=models.CharField(blank=True, max_length=255, verbose_name='الاسم بالعربي'),
        ),
        migrations.AddField(
            model_name='user',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='الاسم بالإنجليزي'),
        ),
        migrations.CreateModel(
            name='NationalAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, default='المملكة العربية السعودية', max_length=255, verbose_name='الدولة')),
                ('region', models.CharField(blank=True, max_length=255, verbose_name='المنطقة')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='المدينة')),
                ('district', models.CharField(blank=True, max_length=255, verbose_name='الحي')),
                ('street', models.CharField(blank=True, max_length=255, verbose_name='الشارع')),
                ('building_number', models.CharField(blank=True, max_length=4, verbose_name='رقم المبنى')),
                ('postal_code', models.CharField(blank=True, max_length=5, verbose_name='الرمز البريدي')),
                ('additional_number', models.CharField(blank=True, max_length=4, verbose_name='الرقم الإضافي')),
                ('plot_number', models.CharField(blank=True, max_length=255, verbose_name='رقم القطعة')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='national_address', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'عنوان وطني',
                'verbose_name_plural': 'العناوين الوطنية',
            },
        ),
    ]
