# Generated by Django 5.2.17 on 2026-09-07 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_migrate_company_addresses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='building_number',
        ),
        migrations.RemoveField(
            model_name='company',
            name='city',
        ),
        migrations.RemoveField(
            model_name='company',
            name='district',
        ),
        migrations.RemoveField(
            model_name='company',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='company',
            name='street',
        ),
    ]
