# Generated by Django 5.2.17 on 2026-09-13 12:50

import apps.core.uploads
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_remove_company_address_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("cr", "السجل التجاري"),
                            ("tax", "الشهادة الضريبية"),
                            ("id", "صورة الهوية"),
                            ("iban", "صورة الآيبان"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.core.uploads.customer_document_path
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=200)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "وثيقة عميل",
                "verbose_name_plural": "وثائق العملاء",
                "ordering": ("-uploaded_at",),
                "indexes": [
                    models.Index(
                        fields=["user", "kind", "-uploaded_at"],
                        name="accounts_cu_user_id_bff1cb_idx",
                    )
                ],
            },
        ),
    ]
