# Generated by Django 5.2.17 on 2026-09-13 20:36

import apps.accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_customerdocument"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(
                blank=True,
                default="",
                max_length=32,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[A-Za-z0-9][A-Za-z0-9._-]{2,31}$",
                        "اسم الدخول: من ٣ إلى ٣٢ محرفاً، حروفاً لاتينية وأرقاماً و. _ - ويُحفظ بحروفٍ صغيرة.",
                    ),
                    apps.accounts.models.not_a_phone_number,
                ],
                verbose_name="اسم الدخول",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                condition=models.Q(("username", ""), _negated=True),
                fields=("username",),
                name="user_username_unique_when_set",
                violation_error_message="اسم الدخول مستعمَل لحسابٍ آخر",
            ),
        ),
    ]
