# Generated by Django 5.2.17 on 2026-09-28 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_name_the_existing_staff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="full_name",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="الاسم الكامل"
            ),
        ),
    ]
