# Generated by Django 5.2.17 on 2026-08-29 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auctions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("is_withdrawn", models.BooleanField(default=False)),
                ("placed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bidder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bids",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "superseded_by",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supersedes",
                        to="bidding.bid",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bids",
                        to="auctions.vehicle",
                    ),
                ),
            ],
            options={
                "ordering": ["-amount", "placed_at"],
                "indexes": [
                    models.Index(
                        fields=["vehicle", "-amount"],
                        name="bidding_bid_vehicle_b46a1e_idx",
                    ),
                    models.Index(
                        fields=["bidder", "-placed_at"],
                        name="bidding_bid_bidder__04f68d_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("amount__gt", 0)), name="bid_is_positive"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("is_withdrawn", False), ("superseded_by__isnull", True)
                        ),
                        fields=("vehicle", "bidder"),
                        name="one_live_bid_per_bidder_per_vehicle",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="BidRefusal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("auction_not_live", "المزاد ليس جارياً"),
                            ("auction_ended", "المزاد انتهى"),
                            ("vehicle_not_biddable", "المركبة غير قابلة للمزايدة"),
                            ("below_floor", "أقل من الحد الأدنى"),
                            ("no_deposit", "لا يوجد تأمين متاح"),
                            ("unpaid_dues", "عليه مستحقات غير مسدَّدة"),
                            ("phone_not_verified", "الجوال غير موثّق"),
                            ("profile_incomplete", "الملف غير مكتمل"),
                            ("own_vehicle", "المركبة تخصّه"),
                        ],
                        max_length=32,
                    ),
                ),
                ("detail", models.CharField(blank=True, max_length=500)),
                (
                    "insurance_free",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "insurance_held",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "insurance_locked",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "outstanding_dues",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("refused_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bidder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bid_refusals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refusals",
                        to="auctions.vehicle",
                    ),
                ),
            ],
            options={
                "ordering": ["-refused_at"],
                "indexes": [
                    models.Index(
                        fields=["bidder", "-refused_at"],
                        name="bidding_bid_bidder__9bc337_idx",
                    ),
                    models.Index(
                        fields=["reason", "-refused_at"],
                        name="bidding_bid_reason_e6a489_idx",
                    ),
                ],
            },
        ),
    ]
