# Generated by Django 5.2.17 on 2026-09-02 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_vehicle_condition_vehicle_fuel_type_and_more"),
        ("bidding", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="bid",
            name="one_live_bid_per_bidder_per_vehicle",
        ),
        migrations.RemoveField(
            model_name="bid",
            name="superseded_by",
        ),
        migrations.AddField(
            model_name="bid",
            name="is_superseded",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="bid",
            name="supersedes",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="superseded_by",
                to="bidding.bid",
            ),
        ),
        migrations.AddField(
            model_name="bid",
            name="withdrawn_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="bid",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_superseded", False), ("is_withdrawn", False)),
                fields=("vehicle", "bidder"),
                name="one_live_bid_per_bidder_per_vehicle",
            ),
        ),
        migrations.AddConstraint(
            model_name="bid",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("is_withdrawn", False), ("withdrawn_at__isnull", True)),
                    models.Q(("is_withdrawn", True), ("withdrawn_at__isnull", False)),
                    _connector="OR",
                ),
                name="a_withdrawn_bid_names_its_moment",
            ),
        ),
    ]
