# Generated by Django 5.2.17 on 2026-09-05 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0002_bid_supersession_and_withdrawal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidrefusal',
            name='reason',
            field=models.CharField(choices=[('auction_not_live', 'المزاد ليس جارياً'), ('auction_ended', 'المزاد انتهى'), ('vehicle_not_biddable', 'المركبة غير قابلة للمزايدة'), ('below_floor', 'أقل من الحد الأدنى'), ('no_deposit', 'لا يوجد تأمين متاح'), ('unpaid_dues', 'عليه مستحقات غير مسدَّدة'), ('phone_not_verified', 'الجوال غير موثّق'), ('profile_incomplete', 'الملف غير مكتمل'), ('own_vehicle', 'المركبة تخصّه'), ('refund_pending', 'تأمينه مطلوبٌ استرداده')], max_length=32),
        ),
    ]
