# Generated by Django 5.2.17 on 2026-09-16 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="المعرّف"
                    ),
                ),
                ("name_ar", models.CharField(max_length=100, verbose_name="الاسم")),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="الاسم (إنجليزي)"
                    ),
                ),
                (
                    "is_open",
                    models.BooleanField(default=True, verbose_name="يستقبل محادثات"),
                ),
                (
                    "position",
                    models.PositiveSmallIntegerField(default=0, verbose_name="الترتيب"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "قسم دعم",
                "verbose_name_plural": "أقسام الدعم",
                "ordering": ("position", "id"),
            },
        ),
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guest_name",
                    models.CharField(
                        blank=True, max_length=190, verbose_name="اسم الزائر"
                    ),
                ),
                (
                    "language",
                    models.CharField(default="ar", max_length=2, verbose_name="اللغة"),
                ),
                (
                    "opened_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="بدأت"),
                ),
                (
                    "closed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="أُغلقت"),
                ),
                (
                    "closed_reason",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="سببُ الإغلاق"
                    ),
                ),
                (
                    "last_message_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="آخر رسالة"
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_conversations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="مُسنَدة إلى",
                    ),
                ),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="closed_conversations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أغلقها",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="support_conversations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="العميل",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="conversations",
                        to="support.department",
                        verbose_name="القسم",
                    ),
                ),
            ],
            options={
                "verbose_name": "محادثة دعم",
                "verbose_name_plural": "محادثات الدعم",
                "ordering": ("-last_message_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sender_kind",
                    models.CharField(
                        choices=[
                            ("customer", "العميل"),
                            ("staff", "الموظّف"),
                            ("system", "النظام"),
                        ],
                        max_length=10,
                        verbose_name="نوع الكاتب",
                    ),
                ),
                ("body", models.TextField(verbose_name="النص")),
                (
                    "read_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="قُرئت"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="الوقت"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="support_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="الكاتب",
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="support.conversation",
                        verbose_name="المحادثة",
                    ),
                ),
            ],
            options={
                "verbose_name": "رسالة دعم",
                "verbose_name_plural": "رسائل الدعم",
                "ordering": ("id",),
            },
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["department", "-last_message_at"],
                name="support_conv_dept_recent",
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                condition=models.Q(("closed_at__isnull", True)),
                fields=["closed_at"],
                name="support_conv_open",
            ),
        ),
        migrations.AddConstraint(
            model_name="conversation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("customer__isnull", False),
                    models.Q(("guest_name", ""), _negated=True),
                    _connector="OR",
                ),
                name="support_conv_has_a_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="conversation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("closed_by__isnull", True),
                    ("closed_at__isnull", False),
                    _connector="OR",
                ),
                name="support_conv_closed_by_needs_a_time",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["conversation", "id"], name="support_msg_thread"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                condition=models.Q(
                    ("read_at__isnull", True), ("sender_kind", "customer")
                ),
                fields=["conversation"],
                name="support_msg_unread",
            ),
        ),
        migrations.AddConstraint(
            model_name="message",
            constraint=models.CheckConstraint(
                condition=models.Q(("body", ""), _negated=True),
                name="support_msg_has_a_body",
            ),
        ),
        migrations.AddConstraint(
            model_name="message",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("sender_kind", "staff"), _negated=True),
                    ("author__isnull", False),
                    _connector="OR",
                ),
                name="support_msg_staff_reply_has_an_author",
            ),
        ),
    ]
